### ISSUE TITLE
Not using all channels 

### ISSUE THREAD

**Issue by RubberDinero** [nick-less/sonoff-4ch-homekit#1]
New to github, so not sure if this is the right place to ask.
If I'm not using all 4 channels, how will this appear on Home app? Is there a way to only add 2-3 channels to Home? And would it be possible to add the other channels later? (This to me seems just like a simple delete the entry and re-add, but maybe there is a faster way)

**Comment by nick-less** [comment]
Well, the buttons are added to homekit when the device is paired. It might be possible to pair every buttons as its own device, but this would lead to memory problems very quickly, since pairing involves ssl and other expensive operations...
