### ISSUE TITLE
Connection problem after compiling code

### ISSUE THREAD

**Issue by OoHerbethoO** [nick-less/sonoff-4ch-homekit#3]
Good evening, first congratulations on the initiative and the great work!
I'm having a problem compiling the cloned code, always from the problem to connect to the Home app on my iPhone. Could you help me with what might be causing the error?

**Comment by nick-less** [comment]
Well, this is just a variation of maximkulkin homekit code so he's the one to praise. anyway, whats your problem, please supply commands and system used to compile, error messages and so on...

**Comment by OoHerbethoO** [comment]
Thanks for the comeback.
I'll attach the screenshot of the error that occurs in the pairing.
![106078EE-6E70-42CE-9ED1-1E07B32F981A](https://user-images.githubusercontent.com/16544588/65457763-acbf8e00-de22-11e9-9bdf-0d2a0f14a941.png)
